### ISSUE TITLE
Matching wide to long

### ISSUE THREAD

**Issue by andkov** [IALSA/IALSA-2015-Portland#135]
@wibeasley , some of values don't match between long and wide formats. Here's an example. Any idea what might be the issue?

![image](https://cloud.githubusercontent.com/assets/2608073/16457262/b0c3bef0-3dcf-11e6-8006-1370c49744cc.png)

**Comment by wibeasley** [comment]
Thanks for checking on me.  There's a lot of moving parts in 110k rows, it gets confusing so I easily could have made a mistake.  However in this case, I think everything is working correctly.  That first/long table is *already filtering* on 'gait' (otherwise the 110k rows were freezing the browser and it was unusable).

Because a filter is already in place, your first screen shot is showing only `gait x block`, and not showing all three of `'gait x block' | 'grip x block' | 'perf+block'`.  To get the window you want, you have to step inside the program.  

![image](https://cloud.githubusercontent.com/assets/1372890/16458942/9f240a08-3de6-11e6-8b8a-f143e39e9a05.png)
![image](https://cloud.githubusercontent.com/assets/1372890/16458964/b618962a-3de6-11e6-995d-458a29fb500b.png)

![image](https://cloud.githubusercontent.com/assets/1372890/16458984/cd009946-3de6-11e6-8e13-1114efa68478.png)

I'm glad you brought this up, because this shows the scenario that supports @ampiccinin & @GracielaMuniz's desire to collapse the `block` growth model parameters across multiple models (ie, paired with `gait`, `grip`, & `pef`).

**Comment by wibeasley** [comment]
If you want to compare yourself, you have to be content with something crossed with `gait`, such as:


# est
![image](https://cloud.githubusercontent.com/assets/1372890/16458396/8a5d2dae-3de4-11e6-82dd-ce3268ea5bdf.png)

# se
![image](https://cloud.githubusercontent.com/assets/1372890/16458333/5a00bbe4-3de4-11e6-98e5-4d33071f706c.png)
