### ISSUE TITLE
Table 1- descriptives

### ISSUE THREAD

**Issue by eduggan** [IALSA/IALSA-2015-Portland#166]
@andkov @ampiccinin 

I need editable versions of table 1 for each study for the manuscript. Also, when  clicking on each study, as listed on IALSA-2015-Portland/projects/pulmonary-cognitive/ to produce table 1, each is not clearly labeled with the study title and at least one is mis-matched (clicking on NAS produces the LASA table 1).

**Comment by andkov** [comment]
@eduggan 

The table 1 files (doc + pdf) are all located here : https://github.com/IALSA/IALSA-2015-Portland/tree/master/studies/table_1_descriptives . From browser, it's easier to view a PDF rather then word, hence the two versions. 

If you make corrections to the word files, please make sure to save it as PDF so that there is no discrepancies between word and pdf versions. If, however, you want it for other transformation or purposes, please DO NOT save them in this directory to avoid confusion. 

Let me know if you have any questions!
