### ISSUE TITLE
Fixing links and double-checking included studies

### ISSUE THREAD

**Issue by ampiccinin** [IALSA/IALSA-2015-Portland#175]
@andkov  - it has just been noted that some pieces of the grip-cognitive area are being haunted by the pulmonary outputs as well as some other issues. Andrea Zammit is trying to access these now to complete the grip-cog paper, so the sooner you could correct these the better. Thanks!

- ILSE, LASA and NuAge are missing on the grip-cognition page
- correlation-3-grip-focus and -full both actually link to the pulmonary file output. The external and internal titles are "grip", but in the table, the Physical variable is listed as pef or fev.
-  domain map on grip page gives a 404

*( also - please correct the study associated with Chenkai's name. It was initially HABC, but now it is HRS. To be thorough, it would be worth noting that initially Chenkai's plan was to use HABC, but the way we have it listed now looks like an error).

Similarly, the MAP study is still labeled "RACD" on our main Portland page. I tried to edit these, but apparently do not have permission (or don't understand the "edit" button...). On some of the sub-pages, RADC has been edited to MAP, but the alphabetical ordering has not been updated (sorry to be so picky, but it can be confusing).

Thanks!

**Comment by ampiccinin** [comment]
@andkov : NuAge, LASA and ILSE are also missing from Gait, but please fix Grip first, then check through all the links for the more recently created pages.

**Comment by andkov** [comment]
Thanks for the detail instructions, @ampiccinin. I'll get on it today.

**Comment by andkov** [comment]
@ampiccinin, @andreazammit, just to keep you posted, I"m looking at the code. The reports fail to reproduce. Which is not entirely unexpected, but certaintly frustraiting. No cause for worries, just requires a bit more unanticipated (when it really is?) code maintanance on my side. I couldn't do a quick fix I was hoping for: it wasn't just a link issue, the reprot produced a wrong table and i missed it. I think because we were focusing on pulmonary then and grip was sort of a side effect. So i'll have to dive deeply in order to address it, which is a good thing because it's about time I do. I'll take care of the issues listed first, though. 

@ampiccinin , not all studies contributed to all measures. I was adjusting the table of links. (just to clarify, we are talking about this page: https://github.com/IALSA/IALSA-2015-Portland/tree/master/projects/grip-cognitive). So I interpret the missingness of ILSE, LASA and NuAge as meaningful: the models contributed to the pool did not usethis predictor. I"ll be glad to double check; this will also be a good opportunity to remind us what studies contribute to what track. 

`domain map` is not working because the  graph has not been produced yet. This is on my agenda for the Grand Cleaning of IALSA repositories i'm scheduling for this next week. 

`RADC/MAP` - yes, thanks for picking up on these things. Some of these works are leftovers from the earlier times, when I did not know what I was doing to a greater extent. I think i was thinking "RADC" was more general, but I see now why MAP is a better choice. I"ll keep an eye on this as I clean.

**Comment by andkov** [comment]
@ampiccinin , thanks for pointing out the incorrect study names on project READMEs. I think I was focusing on pulmonary at a time and didn't check the materials for other tracks to save time. I'm coming back to the front face of track READMEs to ensure the availability of all materials for publications. 

To offer a bird-eye glimpse at the current state of the `catalog` (the data object holding all processed and groomed model results) at this time, here are contributions, here are the tallies of models from each study, broken down by track. I'll use these lists desing each track's readme.

## All Models
```r
> catalog %>%
+   group_by(process_a, study_name) %>%
+   summarize(n_models=n()) %>%
+   filter(process_a %in% c("gait","tug")) %>%
+   print(n=nrow(.))
Source: local data frame [7 x 3]
Groups: process_a [2]

  process_a study_name n_models
      <chr>      <chr>    <int>
1      gait        eas      120
2      gait       elsa        6
3      gait        hrs       18
4      gait       lasa        6
5      gait        map      152
6      gait       octo      104
7       tug       ilse       43
> catalog %>%
+   group_by(process_a, study_name) %>%
+   summarize(n_models=n()) %>%
+   filter(process_a %in% c("grip")) %>%
+   print(n=nrow(.))
Source: local data frame [9 x 3]
Groups: process_a [1]

  process_a study_name n_models
      <chr>      <chr>    <int>
1      grip        eas      131
2      grip       elsa        4
3      grip        hrs       18
4      grip       ilse       10
5      grip       lasa        6
6      grip        map      152
7      grip      nuage       20
8      grip       octo      104
9      grip      satsa       56
> catalog %>%
+   group_by(process_a, study_name) %>%
+   summarize(n_models=n()) %>%
+   filter(process_a %in% c("fev","pef")) %>%
+   print(n=nrow(.))
Source: local data frame [8 x 3]
Groups: process_a [2]

  process_a study_name n_models
      <chr>      <chr>    <int>
1       fev       elsa        4
2       fev        map      152
3       fev        nas       66
4       fev      satsa      106
5       pef        eas       49
6       pef        hrs       18
7       pef       lasa        6
8       pef       octo      104
```

## `b1 aehplus` models
And here are the same tables, but not counting only the bivariate linear models of type `aehplus`, the one that we use in reporting correlations. 

```r
> catalog %>%
+   filter(model_number=="b1",model_type =="aehplus") %>%
+     group_by(process_a, study_name) %>%
+   summarize(n_models=n()) %>%
+   filter(process_a %in% c("gait","tug")) %>%
+   print(n=nrow(.))
Source: local data frame [7 x 3]
Groups: process_a [2]

  process_a study_name n_models
      <chr>      <chr>    <int>
1      gait        eas       22
2      gait       elsa        6
3      gait        hrs        6
4      gait       lasa        6
5      gait        map       38
6      gait       octo       26
7       tug       ilse       11
> catalog %>%
+   filter(model_number=="b1",model_type =="aehplus") %>%
+     group_by(process_a, study_name) %>%
+   summarize(n_models=n()) %>%
+   filter(process_a %in% c("grip")) %>%
+   print(n=nrow(.))
Source: local data frame [9 x 3]
Groups: process_a [1]

  process_a study_name n_models
      <chr>      <chr>    <int>
1      grip        eas       22
2      grip       elsa        4
3      grip        hrs        6
4      grip       ilse       10
5      grip       lasa        6
6      grip        map       38
7      grip      nuage        4
8      grip       octo       26
9      grip      satsa       20
> catalog %>%
+   filter(model_number=="b1",model_type =="aehplus") %>%
+     group_by(process_a, study_name) %>%
+   summarize(n_models=n()) %>%
+   filter(process_a %in% c("fev","pef")) %>%
+   print(n=nrow(.))
Source: local data frame [8 x 3]
Groups: process_a [2]

  process_a study_name n_models
      <chr>      <chr>    <int>
1       fev       elsa        4
2       fev        map       38
3       fev        nas        8
4       fev      satsa       20
5       pef        eas       22
6       pef        hrs        6
7       pef       lasa        6
8       pef       octo       26
```

**Comment by andkov** [comment]
@ampiccinin , @andreazammit all reports in GRIP has been updated and links corrected. You can access all of them at the project's README: https://github.com/IALSA/IALSA-2015-Portland/tree/master/projects/grip-cognitive
