### ISSUE TITLE
Mismatch in EAS

### ISSUE THREAD

**Issue by andkov** [IALSA/IALSA-2015-Portland#98]
The model names declared as filenames (e.g. "b1_male_aehplus_grip_pef.out") do not match with the definitions in the Mplus script. 

Submitted under name: b1_male_aehplus_grip_pef.out
```
  DEFINE:
    p1=PeakFlowBestOf3_1; p2=PeakFlowBestOf3_2; p3=PeakFlowBestOf3_3;
       p4=PeakFlowBestOf3_4; p5=PeakFlowBestOf3_5; p6=PeakFlowBestOf3_6;
       p7=PeakFlowBestOf3_7; p8=PeakFlowBestOf3_8; p9=PeakFlowBestOf3_9;
  c1=MaxEff_1; c2=MaxEff_2; c3=MaxEff_3; c4=MaxEff_4; c5=MaxEff_5; c6=MaxEff_6;
  c7=MaxEff_7; c8=MaxEff_8; c9=MaxEff_9;
```

Submitted under name: b1_female_aehplus_grip_gait.out
```
  DEFINE:
    p1=MaxEff_1; p2=MaxEff_2; p3=MaxEff_3; p4=MaxEff_4; p5=MaxEff_5; p6=MaxEff_6;
     p7=MaxEff_7; p8=MaxEff_8; p9=MaxEff_9;
  c1=Velocity_1; c2=Velocity_2; c3=Velocity_3; c4=Velocity_4; c5=Velocity_5;
  c6=Velocity_6; c7=Velocity_7; c8=Velocity_8; c9=Velocity_9;
```

Submitted under name: b1_female_aehplus_pef_gait.out
```
  DEFINE:
    p1=PeakFlowBestOf3_1; p2=PeakFlowBestOf3_2; p3=PeakFlowBestOf3_3;
       p4=PeakFlowBestOf3_4; p5=PeakFlowBestOf3_5; p6=PeakFlowBestOf3_6;
       p7=PeakFlowBestOf3_7; p8=PeakFlowBestOf3_8; p9=PeakFlowBestOf3_9;
  c1=Velocity_1; c2=Velocity_2; c3=Velocity_3; c4=Velocity_4; c5=Velocity_5;
  c6=Velocity_6; c7=Velocity_7;
          c8=Velocity_8; c9=Velocity_9;
```

@andreazammit , please double check the variable definitions and re-run if necessary.

**Comment by andreazammit** [comment]
@andkov  not sure what's wrong with my definitions? What am I missing? =/

**Comment by andkov** [comment]
@andreazammit ,  the scripts as they read right now state that in model (let's call it model A) *b1_male_aehplus_grip_pef.out* grip is defined as PeakFlowBestof3 and pef is defined as 
MaxEff. In other words:
(A) - b1_male_aehplus_grip_pef:   
```
grip = PeakFlowBestof3 
pef = MaxEff
```

For other models:

(B) - b1_female_aehplus_grip_gait.out
```
grip = MaxEff
gait = Velocity
```

(C) - b1_female_aehplus_pef_gait.out
b1_female_aehplus_pef_gait.out
```
pef =PeakFlowBestOf3
gait = Velocity
```

Look at grip is defined in (A) and (B). one of these is an typing error.

**Comment by andreazammit** [comment]
@andkov  Crap. I see what I did - the title doesn't match the definitions. I'll re run model A because that's where the error is.

**Comment by andkov** [comment]
Yeah, these are tricky to spot and easy to miss.

**Comment by andreazammit** [comment]
@andkov my github is giving a  lot of trouble. I have deleted it and redownloaded it several time and it is still telling me "failed to sync this branch" 
I am trying to upload my model from my macbook and it's been syncing for the past 15 minutes. 
So both my githubs are not working. 
I tried git push
but nothing.

One weird thing i have on my computer is that i have a "publish" rather than a "sync" button. IS that maybe a feature of the more recent versions?

**Comment by andkov** [comment]
Sorry, @andreazammit ,   I will be able to attend to this only in about four hours, but I would give it some time to sink because right now it has a lot of pictures which increase the size of the repository

**Comment by wibeasley** [comment]
@andreazammit before @andkov gets to it this afternoon, give it the best shot of downloading the full repo.  It sounds like you're syncing/sinking it from scratch?  If so, that's almost a full gigabyte of information.  Unless you have very solid wifi, plug into ethernet.

![image](https://cloud.githubusercontent.com/assets/1372890/10823969/2858422e-7e2c-11e5-979c-9ca8dcb13e6b.png)

**Comment by wibeasley** [comment]
I'm curious how this was resolved.  Last night, my desktop client had trouble merging something that should have been easy.  I think the problem was the desktop client, because the command line had no problems once I restarted the merge operation.  

An hour or two later, the desktop client wanted to update itself for the second time; this makes me think the developers pushed out a change that fixed a problem they introduced earlier that day.

**Comment by andreazammit** [comment]
@wibeasley I synced when I got home - my macbook has no problems syncing but I run my Mplus models on my PC, which is at work and which is the computer on which my GitHub doesn't work. So I have to work between computers to run models and upload them on Github =/ Yesterday, my Macbook had trouble syncing I gather because I was using the wifi at work? Because when I got home it merged straight away...

**Comment by wibeasley** [comment]
Or instead of wifi (like I was guessing yesterday), maybe it was a bug in the client that they fixed later in the day.  Either way, I'm glad it worked out.  You might appreciated this morning's XKCD:

[![git](http://imgs.xkcd.com/comics/git.png)](http://imgs.xkcd.com/comics/git.png)
http://xkcd.com/1597/
http://www.explainxkcd.com/wiki/index.php/1597

**Comment by andreazammit** [comment]
@wibeasley  haha I can relate :)
